version: '3'

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.22.0
    container_name: reverse_proxy
    depends_on:
        - first-app
        - second-app
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse_proxy/index.html:/usr/share/nginx/html/index.html
    ports:
      - 80:80


  first-app:
    image: first-app
    container_name: first-app
    build:
      context: ./first_app
    restart: on-failure


  second-app:
    image: second-app
    container_name: second-app
    build:
      context: ./second_app
    restart: on-failure
